### PR TITLE
onoctree code conversion regex include quote

### PR DESCRIPTION
**Pull request by zheins**
@thomasyu888 Please review

### CODE REVIEW

**Comment by thomasyu888** [comment]
Thanks for the fix.

**Comment by alexbaras** [comment]
Zach


how should we / do you handle oncotree codes that map to multiple cancer types?


-Alex


________________________________

**Comment by zheins** [comment]
@alexbaras Are there any examples of codes that map to multiple type? Each code should only appear once in the tree, and therefore only have one value for `metamaintype` or `CANCER_TYPE`

**Comment by zheins** [comment]
@alexbaras sorry I misspoke - you're right some codes do appear multiple times if they are higher up the tree and have sub types underneath them. These should still all map up to the same `metamaintype`/`CANCER_TYPE` though. If they do not that is a bug in the oncotree.

**Pull request merged**
