### PR TITLE
[GEN-996] convert the clinical template columns from a set to a list

### PR DESCRIPTION
**Pull request by danlu1**
Problem:
Run into ValueError: columns cannot be a set when upgrading to pandas >= 1.5 for `Clinical.preprocess`

Solution:
Convert set to list

Test:
unit test function has been added

### CODE REVIEW

**Review by rxu17 — APPROVED** [review]
LGTM! Great work, would hold off on merging

**Review by thomasyu888 — APPROVED** [review]
🔥 LGTM!

**Comment by rxu17** [comment]
@danlu1 Feel free to merge this after you merge in updates from `develop`!

**Comment by rxu17** [comment]
@danlu1 Feel free to merge in this PR.

**Pull request merged**
