### PR TITLE
fixes to seq-assay-id validation checks

### LINKED ISSUE #435: Make validation of SEQ_ASSAY_IDs case-insensitive
The SEQ_ASSAY_IDs in the assay_information.yaml are being compared to the 'Sample Clinical Database' table (syn7517674), which converts the SEQ_ASSAY_IDs to all uppercase.  If the SEQ_ASSAY_IDs assay_information.yaml contain lowercase characters, they will be erroneously flagged.

### PR DESCRIPTION
**Pull request by hhunterzinck**
Fixes #435

### CODE REVIEW

**Comment by hhunterzinck** [comment]
All tests, including newly added test, pass but linting fails on two files:
genie_registry/assay.py
genie/process_functions.py

**Comment by hhunterzinck** [comment]
All tests, including newly added test, pass but linting fails on one file:
genie/process_functions.py

**Comment by hhunterzinck** [comment]
@thomasyu888  all tests and linting now pass

**Comment by thomasyu888** [comment]
The processing needs to change for this too right? Or is there already functions to change to uppercase and replace the _ with -

**Comment by hhunterzinck** [comment]
@thomasyu888 accounting for '_' to '-' now.  Any other formatting changes made to the SEQ_ASSAY_ID before upload to the Sample Clinical Database that we should account for?

**Comment by thomasyu888** [comment]
Not sure. We just need to make sure the processing function in assay info does those transformations.

**Comment by hhunterzinck** [comment]
@thomasyu888 Sure, we can make sure the processing functions for the assay files conduct the same functionality.  Would merging these changes to the validation function first affect the rest of the pipeline, though?  I just want to make sure we are not erroneously flagging these files for changes when we don't actually want the uploaders to make any changes.

**Comment by thomasyu888** [comment]
The changes that are pulled into develop arent used in production yet. Will have to merge things into main and do a release for the changes to work.

That being said, there shouldn't be any issue except if these transformations aren't done in processing, then they will be uploaded into the assay table with underscores and lower case lettering.

**Comment by hhunterzinck** [comment]
I think these changes are made already during processing, which is why the validation between the uploaded assay_information.yaml and the internal database was flagging the SEQ_ASSAY_IDs as issues.  See: https://github.com/Sage-Bionetworks/Genie/blob/0485b7e1599c4894714a92d5e12e99cc2b0cd02d/genie_registry/assay.py#L61

**Review by thomasyu888 — APPROVED** [review]

**Pull request merged**
