### PR TITLE
DEV: use separate loggers

### LINKED ISSUE #109: Use separate loggers for different modules
Always using the `genie` logger makes it hard to debug. Use separate loggers for each module or script.

### PR DESCRIPTION
**Pull request by kdaily**
Fixes #109

### CODE REVIEW

**Comment by thomasyu888** [comment]
Add `logger.setLevel(logging.INFO)` to `consortium_to_public.py`

**Comment by kdaily** [comment]
Done!

**Review by thomasyu888 — APPROVED** [review]

**Comment by thomasyu888** [comment]
Thanks! Couple more
* write_invalid_reasons.py
* dashboard_table_updater.py

**Comment by kdaily** [comment]
done

**Review by thomasyu888 — APPROVED** [review]

**Pull request merged**
